import assert from 'node:assert/strict';
import fs from 'node:fs';
import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || (process.platform === 'win32' ? 'C:/Program Files/Google/Chrome/Application/chrome.exe' : undefined), headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', colorScheme: 'light' });
const page = await context.newPage();
const base = process.env.TEST_BASE_URL || 'http://localhost:5174';
fs.mkdirSync('reports', { recursive: true });
const errors = [], requests = [], layouts = [], accessibility = [];
page.on('pageerror', error => errors.push(error.message));
let behaviour = 'failure';
await page.route('**/api/contact', async route => {
  if (route.request().method() === 'GET') return route.fulfill({ json: { readyAfterMs: 0 } });
  requests.push(route.request().postDataJSON());
  if (behaviour === 'network') return route.abort('failed');
  if (behaviour === 'validation') return route.fulfill({ status: 422, json: { message: 'Please check your message.', errors: { message: 'Please provide more detail.' } } });
  if (behaviour === 'failure') return route.fulfill({ status: 502, json: { message: 'The enquiry service is unavailable. Please retry.' } });
  await new Promise(resolve => setTimeout(resolve, 600));
  return route.fulfill({ json: { message: 'Your enquiry has been received by WOY Consulting.' } });
});
try {
  await page.goto(base + '/contact', { waitUntil: 'load' });
  await page.getByRole('button', { name: 'Essential only', exact: true }).click();
  assert.equal(await page.title(), 'Start a conversation | WOY Consulting');
  const send = page.getByRole('button', { name: 'Send enquiry', exact: true });
  await send.click();
  assert.equal(await page.evaluate(() => document.activeElement.id), 'f-name');
  assert.equal(requests.length, 0);
  await page.locator('#f-name').fill('Website Test');
  await page.locator('#f-email').fill('bad-address');
  await send.click();
  assert.equal(await page.locator('#f-email').evaluate(el => el.validity.typeMismatch), true);
  await page.locator('#f-email').fill('visitor@example.test');
  await page.locator('#f-message').fill('A short');
  await send.click();
  assert.equal(requests.length, 0);
  await page.locator('#f-message').fill('We would like to discuss leadership alignment.\nThis is a test enquiry.');
  await send.click();
  assert.equal(await page.evaluate(() => document.activeElement.id), 'f-consent');
  assert.equal(requests.length, 0);
  await page.locator('#f-consent').focus();
  await page.keyboard.press('Space');
  assert.equal(await page.locator('#f-consent').isChecked(), true);
  await send.click();
  await page.getByRole('alert').filter({ hasText: 'enquiry service is unavailable' }).waitFor();
  assert.equal(await page.locator('#f-name').inputValue(), 'Website Test');
  assert.equal(await page.locator('#f-consent').isChecked(), true);
  const firstId = requests[0].id;
  assert.match(firstId, /^[0-9a-f-]{36}$/);
  assert.equal(requests[0].organisation, '');
  assert.equal(requests[0].consent, true);
  assert.equal(requests[0].privacyNoticeVersion, '2026-09-25');
  behaviour = 'network';
  await send.click();
  await page.getByRole('alert').filter({ hasText: 'could not confirm receipt' }).waitFor();
  assert.equal(requests[1].id, firstId, 'Unchanged retry retains UUID');
  behaviour = 'validation';
  await send.click();
  await page.getByRole('alert').filter({ hasText: 'check your message' }).waitFor();
  assert.equal(await page.locator('#f-message').getAttribute('aria-invalid'), 'true');
  assert.equal(await page.locator('#err-message').textContent(), 'Please provide more detail.');
  assert.equal(await page.evaluate(() => document.activeElement.id), 'f-message');
  await page.locator('#f-message').fill('We would like to discuss leadership alignment and a practical roadmap.');
  behaviour = 'success';
  const before = await send.boundingBox();
  await page.locator('form').evaluate(form => { form.requestSubmit(); form.requestSubmit(); });
  const sending = page.getByRole('button', { name: 'Sending your enquiry…', exact: true });
  await sending.waitFor();
  assert.equal(await sending.isDisabled(), true);
  const during = await sending.boundingBox();
  assert.equal(during.height, before.height);
  assert.equal(during.width, before.width);
  await page.getByRole('status').filter({ hasText: 'Enquiry received' }).waitFor();
  assert.equal(requests.length, 4, 'Rapid duplicate submission produces one request');
  assert.notEqual(requests[3].id, firstId, 'Edited payload gets a new UUID');
  assert.match(await page.getByRole('status').filter({ hasText: 'Enquiry received' }).textContent(), /received by WOY Consulting/);
  assert.equal(new URL(page.url()).pathname, '/contact');
  await page.getByRole('button', { name: 'Send another enquiry' }).click();
  assert.equal(await page.locator('#f-name').inputValue(), '');
  assert.equal(await page.locator('#f-consent').isChecked(), false);
  await page.locator('#f-name').fill('Another Visitor');
  await page.locator('#f-email').fill('another@example.test');
  await page.locator('#f-message').fill('Another leadership enquiry for validation.');
  await page.locator('#f-consent').check();
  await send.click();
  await page.getByRole('status').filter({ hasText: 'Enquiry received' }).waitFor();
  assert.notEqual(requests[4].id, requests[3].id, 'New enquiry gets a fresh UUID');
  await page.getByRole('button', { name: 'Send another enquiry' }).click();
  const privacy = page.getByRole('link', { name: /Privacy Policy \(review draft\)/ });
  assert.equal(await privacy.getAttribute('href'), '/privacy');
  assert.equal(await privacy.getAttribute('target'), '_blank');
  assert.match(await privacy.textContent(), /opens in a new tab/);
  const privacyResponse = await page.request.get(base + '/privacy');
  assert.equal(privacyResponse.status(), 200);
  assert.equal(new URL(privacyResponse.url()).pathname, '/privacy-policy');
  for (const mode of ['light', 'dark']) {
    await page.addStyleTag({ content: '*,*::before,*::after { transition:none!important; }' });
    if (await page.locator('html').getAttribute('data-theme') !== mode) await page.getByRole('button', { name: `Switch to ${mode} theme`, exact: true }).click();
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    for (const width of [320, 390, 700, 768, 1080, 1440]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true, `No overflow ${mode}/${width}`);
      const footer = page.getByRole('contentinfo');
      assert.equal(await footer.locator('h2 em').evaluate(el => getComputedStyle(el).color), 'rgb(205, 20, 33)');
      assert.equal(await footer.getByRole('link', { name: 'Start a conversation', exact: true }).getAttribute('href'), '/contact');
      assert.equal(await footer.getByRole('link', { name: 'hello@woyconsulting.com', exact: true }).getAttribute('href'), 'mailto:hello@woyconsulting.com');
      layouts.push({ mode, width, footerHeight: (await footer.boundingBox()).height });
      if (width === 390 || width === 1440) {
        await page.locator('main').screenshot({ path: `reports/contact-${mode}-${width}.png` });
        await footer.screenshot({ path: `reports/footer-${mode}-${width}.png` });
      }
    }
    const axe = await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();
    accessibility.push({ mode, violations: axe.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })) });
    assert.equal(axe.violations.filter(v => v.id !== 'color-contrast').length, 0, 'No non-contrast accessibility violations');
  }
  assert.deepEqual(errors, []);
  fs.mkdirSync('reports', { recursive: true });
  fs.writeFileSync('reports/contact-recreation-review.json', JSON.stringify({ requests: requests.length, states: ['native-required','email','message','consent','server-field-error','server-failure','network-failure','retry','busy','duplicate','success','reset'], errors, layouts, accessibility }, null, 2));
  console.log(JSON.stringify({ requests: requests.length, layouts: layouts.length, errors, accessibility }));
} finally { await browser.close(); }
