/* eslint-disable @next/next/no-img-element -- Preserve the source artwork and display-only cropping. */
import { ArrowUpRight } from 'lucide-react';
import Link from 'next/link';
import { cases, type CaseStudy, people, steps } from '@/lib/recreation-content';

export function Logo(){return <span className="logo-window"><img src="/assets/woy-logo.png" alt="WOY Consulting" width="1667" height="980"/></span>}
export function TextLink({href,children}:{href:string;children:React.ReactNode}){return <Link className="text-link" href={href}>{children}<ArrowUpRight size={17} aria-hidden="true"/></Link>}
export function PrimaryLink({href,children}:{href:string;children:React.ReactNode}){return <Link className="primary-link" href={href}>{children}<ArrowUpRight size={18} aria-hidden="true"/></Link>}
export function PageIntro({label,title,children}:{label:string;title:React.ReactNode;children?:React.ReactNode}){return <section className="wrap page-intro"><p className="eyebrow red">{label}</p><h1>{title}</h1>{children&&<div className="page-intro-description">{children}</div>}</section>}
export function CaseCard({item,index=0}:{item:CaseStudy;index?:number}){return <Link className="case-card" href={`/work/${item.slug}`}><div className={`case-cover ${item.theme}`}><div className="case-cover-top"><span>{item.industry}</span><span>{String(index+1).padStart(2,'0')} /</span></div><div className="case-cover-title">{item.cover.split('\n').map((line,i)=><span key={i}>{line}</span>)}</div><div className="case-cover-bottom">{item.strap}</div></div><p className="case-meta">{item.industry}</p><div className="case-card-title"><h3>{item.title}</h3><ArrowUpRight size={22} aria-hidden="true"/></div><p>{item.summary}</p></Link>}
export function PersonCard({person}:{person:typeof people[number]}){return <Link className="person-card" href={`/practitioners#${person.slug}`}><div className={`portrait portrait-${person.slug}`}><img src={`/assets/${person.image}`} alt={person.name} loading="lazy"/></div><div className="person-card-title"><h3>{person.name}</h3><ArrowUpRight size={20} aria-hidden="true"/></div><p className="person-role">{person.role}</p><p className="muted">{person.focus}</p></Link>}
export function FourSteps(){return <div className="steps-grid">{steps.map((s,i)=><div className="step" key={s.name}><span className="step-number">0{i+1}</span><h3>{s.name}</h3><p>{s.text}</p></div>)}</div>}
export function RelatedWork({exclude}:{exclude?:string}){return <section className="wrap section related-work"><div className="section-head"><h2>More perspectives.<br/>More possibilities.</h2><TextLink href="/work">All selected work</TextLink></div><div className="case-grid">{cases.filter(c=>c.slug!==exclude).slice(0,2).map((c,i)=><CaseCard item={c} index={i} key={c.slug}/>)}</div></section>}
